[package]
name = "gobang"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[workspace]
members = [
    "crates/lib_gobang"
]

[dependencies]
lib_gobang = { path = "crates/lib_gobang", version = "0.1.0" }
